fix: add @staticmethod decorator to asm_thumb functions
The @micropython.asm_thumb decorated functions don't take 'self' as a parameter,
but were being called as instance methods. This caused Python to pass 'self'
automatically, resulting in:
  TypeError: function takes 4 positional arguments but 5 were given

Fixed by adding @staticmethod decorator to both:
- _asm_memset
- _asm_hline_mono_vlsb_set

This prevents Python from passing 'self' as the first argument when these
functions are called via self._asm_*(...) syntax.